package stages_test

import (
	"path/filepath"
	"strings"
	"testing"

	. "github.com/onsi/gomega"

	"github.com/theunrepentantgeek/code-visualizer/internal/canvas"
	"github.com/theunrepentantgeek/code-visualizer/internal/config"
	"github.com/theunrepentantgeek/code-visualizer/internal/stages"
)

func TestApplyFooter_NilCanvas_ReturnsNil(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	s := &fakeState{common: stages.CommonState{
		Canvas:     nil,
		RootConfig: config.New(),
	}}

	g.Expect(stages.ApplyFooter[*fakeState](s)).To(Succeed())
}

func TestApplyFooter_NilRootConfig_ReturnsNil(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	s := &fakeState{common: stages.CommonState{
		Canvas:     canvas.NewCanvas(100, 100),
		RootConfig: nil,
	}}

	g.Expect(stages.ApplyFooter[*fakeState](s)).To(Succeed())
}

func TestApplyFooter_FooterHidden_NoFooterOnCanvas(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()
	cfg.OverrideHideFooter(true)

	cv := canvas.NewCanvas(800, 600)
	s := &fakeState{common: stages.CommonState{
		Canvas:     cv,
		RootConfig: cfg,
	}}

	g.Expect(stages.ApplyFooter[*fakeState](s)).To(Succeed())
	g.Expect(cv.FooterText()).To(BeEmpty())
}

func TestApplyFooter_FooterWithText_SetsCanvasFooter(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()
	cfg.OverrideFooterText("Generated by codeviz")

	cv := canvas.NewCanvas(800, 600)
	s := &fakeState{common: stages.CommonState{
		Canvas:     cv,
		RootConfig: cfg,
	}}

	g.Expect(stages.ApplyFooter[*fakeState](s)).To(Succeed())
	g.Expect(cv.FooterText()).NotTo(BeEmpty())
	g.Expect(cv.FooterText()).To(ContainSubstring("Generated by codeviz"))
}

func TestApplyFooter_TemplateSubstitution_DateIsReplaced(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()
	cfg.OverrideFooterText("Generated at $date and $time")

	cv := canvas.NewCanvas(800, 600)
	s := &fakeState{common: stages.CommonState{
		Canvas:     cv,
		RootConfig: cfg,
	}}

	g.Expect(stages.ApplyFooter[*fakeState](s)).To(Succeed())

	text := cv.FooterText()
	g.Expect(text).NotTo(ContainSubstring("$date"))
	g.Expect(text).NotTo(ContainSubstring("$time"))
	g.Expect(strings.HasPrefix(text, "Generated at ")).To(BeTrue())
}

func TestApplyFooter_DefaultConfig_SetsFooter(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()

	cv := canvas.NewCanvas(800, 600)
	s := &fakeState{common: stages.CommonState{
		Canvas:     cv,
		RootConfig: cfg,
	}}

	g.Expect(stages.ApplyFooter[*fakeState](s)).To(Succeed())
	g.Expect(cv.FooterText()).NotTo(BeEmpty())
}

func TestApplyFooter_FooterRendersWithoutError(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()
	cfg.OverrideFooterText("Test footer at $date")

	cv := canvas.NewCanvas(400, 300)
	s := &fakeState{common: stages.CommonState{
		Canvas:     cv,
		RootConfig: cfg,
		Output:     filepath.Join(t.TempDir(), "out.png"),
	}}

	g.Expect(stages.ApplyFooter[*fakeState](s)).To(Succeed())
	g.Expect(stages.WriteCanvas[*fakeState](s)).To(Succeed())
}

func TestEffectiveFooterHeight_NilConfig_ReturnsZero(t *testing.T) {
t.Parallel()
g := NewGomegaWithT(t)

g.Expect(stages.EffectiveFooterHeight(nil)).To(Equal(0))
}

func TestEffectiveFooterHeight_FooterHidden_ReturnsZero(t *testing.T) {
t.Parallel()
g := NewGomegaWithT(t)

cfg := config.New()
cfg.OverrideHideFooter(true)

g.Expect(stages.EffectiveFooterHeight(cfg)).To(Equal(0))
}

func TestEffectiveFooterHeight_FooterShown_ReturnsPositive(t *testing.T) {
t.Parallel()
g := NewGomegaWithT(t)

cfg := config.New()

height := stages.EffectiveFooterHeight(cfg)
g.Expect(height).To(BeNumerically(">", 0))
g.Expect(height).To(Equal(int(canvas.FooterReservedHeight)))
}
