package stages_test

import (
	"path/filepath"
	"strings"
	"testing"

	. "github.com/onsi/gomega"

	"github.com/theunrepentantgeek/code-visualizer/internal/canvas"
	"github.com/theunrepentantgeek/code-visualizer/internal/config"
	"github.com/theunrepentantgeek/code-visualizer/internal/stages"
)

func TestApplyFooter_NilCanvas_ReturnsNil(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	c := &stages.CommonState{Canvas: nil, RootConfig: config.New()}
	g.Expect(stages.ApplyFooter(c)).To(Succeed())
}

func TestApplyFooter_NilRootConfig_ReturnsNil(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	c := &stages.CommonState{Canvas: canvas.NewCanvas(100, 100), RootConfig: nil}
	g.Expect(stages.ApplyFooter(c)).To(Succeed())
}

func TestApplyFooter_FooterHidden_NoFooterOnCanvas(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()
	cfg.OverrideHideFooter(true)

	cv := canvas.NewCanvas(800, 600)
	c := &stages.CommonState{Canvas: cv, RootConfig: cfg}

	g.Expect(stages.ApplyFooter(c)).To(Succeed())
	g.Expect(cv.FooterText()).To(BeEmpty())
}

func TestApplyFooter_FooterWithText_SetsCanvasFooter(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()
	cfg.OverrideFooterText("Generated by codeviz")

	cv := canvas.NewCanvas(800, 600)
	c := &stages.CommonState{Canvas: cv, RootConfig: cfg}

	g.Expect(stages.ApplyFooter(c)).To(Succeed())
	g.Expect(cv.FooterText()).NotTo(BeEmpty())
	g.Expect(cv.FooterText()).To(ContainSubstring("Generated by codeviz"))
}

func TestApplyFooter_TemplateSubstitution_DateIsReplaced(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()
	cfg.OverrideFooterText("Generated at $date and $time")

	cv := canvas.NewCanvas(800, 600)
	c := &stages.CommonState{Canvas: cv, RootConfig: cfg}

	g.Expect(stages.ApplyFooter(c)).To(Succeed())

	text := cv.FooterText()
	g.Expect(text).NotTo(ContainSubstring("$date"))
	g.Expect(text).NotTo(ContainSubstring("$time"))
	g.Expect(strings.HasPrefix(text, "Generated at ")).To(BeTrue())
}

func TestApplyFooter_DefaultConfig_SetsFooter(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cv := canvas.NewCanvas(800, 600)
	c := &stages.CommonState{Canvas: cv, RootConfig: config.New()}

	g.Expect(stages.ApplyFooter(c)).To(Succeed())
	g.Expect(cv.FooterText()).NotTo(BeEmpty())
}

func TestApplyFooter_FooterRendersWithoutError(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()
	cfg.OverrideFooterText("Test footer at $date")

	cv := canvas.NewCanvas(400, 300)
	c := &stages.CommonState{
		Canvas:     cv,
		RootConfig: cfg,
		Output:     filepath.Join(t.TempDir(), "out.png"),
	}

	g.Expect(stages.ApplyFooter(c)).To(Succeed())
	g.Expect(stages.WriteCanvas(c)).To(Succeed())
}

func TestEffectiveFooterHeight_NilConfig_ReturnsZero(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	g.Expect(stages.EffectiveFooterHeight(nil)).To(Equal(0))
}

func TestEffectiveFooterHeight_FooterHidden_ReturnsZero(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()
	cfg.OverrideHideFooter(true)

	g.Expect(stages.EffectiveFooterHeight(cfg)).To(Equal(0))
}

func TestEffectiveFooterHeight_FooterShown_ReturnsPositive(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()

	height := stages.EffectiveFooterHeight(cfg)
	g.Expect(height).To(BeNumerically(">", 0))
	g.Expect(height).To(Equal(int(canvas.FooterReservedHeight)))
}

func TestApplyTitle_NilCanvas_ReturnsNil(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	c := &stages.CommonState{
		Canvas:     nil,
		RootConfig: config.New(),
	}

	g.Expect(stages.ApplyTitle(c)).To(Succeed())
}

func TestApplyTitle_NilRootConfig_ReturnsNil(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	c := &stages.CommonState{
		Canvas:     canvas.NewCanvas(100, 100),
		RootConfig: nil,
	}

	g.Expect(stages.ApplyTitle(c)).To(Succeed())
}

func TestApplyTitle_NoTitle_NoTitleOnCanvas(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()
	// Default config has no title text; ShowTitle() is false.

	cv := canvas.NewCanvas(800, 600)
	c := &stages.CommonState{
		Canvas:     cv,
		RootConfig: cfg,
	}

	g.Expect(stages.ApplyTitle(c)).To(Succeed())
	g.Expect(cv.TitleText()).To(BeEmpty())
}

func TestApplyTitle_WithTitle_SetsTitleOnCanvas(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()
	cfg.OverrideTitleText("My Project")

	cv := canvas.NewCanvas(800, 600)
	c := &stages.CommonState{
		Canvas:     cv,
		RootConfig: cfg,
	}

	g.Expect(stages.ApplyTitle(c)).To(Succeed())
	g.Expect(cv.TitleText()).To(Equal("My Project"))
}

func TestApplyTitle_TitleHidden_NoTitleOnCanvas(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()
	cfg.OverrideTitleText("My Project")
	hidden := true
	cfg.Title.Hidden = &hidden

	cv := canvas.NewCanvas(800, 600)
	c := &stages.CommonState{
		Canvas:     cv,
		RootConfig: cfg,
	}

	g.Expect(stages.ApplyTitle(c)).To(Succeed())
	g.Expect(cv.TitleText()).To(BeEmpty())
}

func TestEffectiveTitleHeight_NilConfig_ReturnsZero(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	g.Expect(stages.EffectiveTitleHeight(nil)).To(Equal(0))
}

func TestEffectiveTitleHeight_NoTitle_ReturnsZero(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()
	g.Expect(stages.EffectiveTitleHeight(cfg)).To(Equal(0))
}

func TestEffectiveTitleHeight_TitleShown_ReturnsPositive(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := config.New()
	cfg.OverrideTitleText("My Project")

	height := stages.EffectiveTitleHeight(cfg)
	g.Expect(height).To(BeNumerically(">", 0))
	g.Expect(height).To(Equal(int(canvas.TitleReservedHeight)))
}
