imageSize:
    width: 2048
    height: 2048
legend:
    position: bottom-center
treemap:
    fill: file-type
    fillPalette: categorization
    border: file-age
    borderPalette: foliage
radial:
    labels: all
bubbletree:
    labels: folders
fileFilter:
    - pattern: .*
      mode: exclude
