imageSize:
    width: 2048
    height: 2048
legend:
    position: bottom-center
tree-map:
    fill: file-type
    fillPalette: categorization
    border: file-age
    borderPalette: foliage
radial:
    labels: all
bubble-tree:
    labels: folders
fileFilter:
    - pattern: .*
      mode: exclude
