width: 2048
height: 2048
treemap:
    fill: file-type
    fillPalette: categorization
    border: file-age
    borderPalette: foliage
    legend: bottom-center
radial:
    labels: all
bubbletree:
    labels: folders
fileFilter:
    - pattern: .*
      mode: exclude
