package config

import (
	"strings"
	"testing"
	"time"

	. "github.com/onsi/gomega"
)

func TestFooter_EffectiveText_DefaultsToAttribution(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	f := &Footer{}
	text := f.EffectiveText()

	g.Expect(text).To(ContainSubstring("Generated by codeviz at "))
	g.Expect(text).To(ContainSubstring(time.Now().Format("2006-01-02")))
}

func TestFooter_EffectiveText_UsesExplicitText(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	custom := "My custom footer"
	f := &Footer{Text: &custom}

	g.Expect(f.EffectiveText()).To(Equal("My custom footer"))
}

func TestFooter_EffectiveText_NilFooter_ReturnsDefault(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	var f *Footer
	text := f.EffectiveText()

	g.Expect(strings.HasPrefix(text, "Generated by codeviz at ")).To(BeTrue())
}

func TestFooter_IsHidden_FalseByDefault(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	f := &Footer{}
	g.Expect(f.IsHidden()).To(BeFalse())
}

func TestFooter_IsHidden_TrueWhenSet(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	hidden := true
	f := &Footer{Hidden: &hidden}
	g.Expect(f.IsHidden()).To(BeTrue())
}

func TestFooter_IsHidden_NilFooter_ReturnsFalse(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	var f *Footer
	g.Expect(f.IsHidden()).To(BeFalse())
}

func TestConfig_OverrideFooterText_SetsText(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := New()
	cfg.OverrideFooterText("custom text")

	g.Expect(cfg.Footer).NotTo(BeNil())
	g.Expect(cfg.Footer.EffectiveText()).To(Equal("custom text"))
}

func TestConfig_OverrideHideFooter_SetsHidden(t *testing.T) {
	t.Parallel()
	g := NewGomegaWithT(t)

	cfg := New()
	cfg.OverrideHideFooter(true)

	g.Expect(cfg.Footer).NotTo(BeNil())
	g.Expect(cfg.Footer.IsHidden()).To(BeTrue())
}
