name: Validate Pull Request
on:
  workflow_dispatch:
    # No configuration, but allows manual triggering

  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]

  merge_group:
    branches:
      - main
    types: [checks_requested]

jobs:
  devcontainer:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build devcontainer image and push
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          imageName: ghcr.io/theunrepentantgeek/code-visualizer-devcontainer
          cacheFrom: ghcr.io/theunrepentantgeek/code-visualizer-devcontainer
          push: ${{ (github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork) && 'always' || 'never' }}

  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build devcontainer image
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          imageName: ghcr.io/theunrepentantgeek/code-visualizer-devcontainer
          cacheFrom: ghcr.io/theunrepentantgeek/code-visualizer-devcontainer
          push: never

      - name: Run task ci in devcontainer
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          imageName: ghcr.io/theunrepentantgeek/code-visualizer-devcontainer
          push: never
          runCmd: task ci
