name: Validate Pull Request
on:
  workflow_dispatch:
    # No configuration, but allows manual triggering

  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]

  merge_group:
    branches:
      - main
    types: [checks_requested]

jobs:
  devcontainer:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build devcontainer image and push
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5 # v0.3.1900000449
        with:
          imageName: ghcr.io/theunrepentantgeek/code-visualizer-devcontainer
          cacheFrom: ghcr.io/theunrepentantgeek/code-visualizer-devcontainer
          push: ${{ (github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork) && 'always' || 'never' }}

  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build devcontainer image
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5 # v0.3.1900000449
        with:
          imageName: ghcr.io/theunrepentantgeek/code-visualizer-devcontainer
          cacheFrom: ghcr.io/theunrepentantgeek/code-visualizer-devcontainer
          push: never

      - name: Run task ci in devcontainer
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5 # v0.3.1900000449
        with:
          imageName: ghcr.io/theunrepentantgeek/code-visualizer-devcontainer
          push: never
          runCmd: task ci
