name: Create Release
on:
  workflow_dispatch:
    # No configuration, but allows manual triggering
  push:
    tags:
      - "v*.*.*" # Trigger on version tags like v1.0.0

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build devcontainer image
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5 # v0.3.1900000449
        with:
          imageName: ghcr.io/theunrepentantgeek/code-visualizer-devcontainer
          cacheFrom: ghcr.io/theunrepentantgeek/code-visualizer-devcontainer
          push: never

      - name: Run task ci in devcontainer
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5 # v0.3.1900000449
        with:
          imageName: ghcr.io/theunrepentantgeek/code-visualizer-devcontainer
          push: never
          runCmd: task ci

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*
          file_glob: true
          asset_name: code-visualizer-${{ github.ref_name }}.zip
          tag: ${{ github.ref_name }}
          overwrite: true
          body: "Release of code-visualizer  version ${{ github.ref_name }}."
